
project_id = "jqkkhwoybcenxqpvodev"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[functions.retell-webhook]
verify_jwt = false

[functions.webhook-monitor]
verify_jwt = true

[functions.fetch-retell-calls]
verify_jwt = true

[functions.sync-calls]
verify_jwt = true

[edge-runtime]
enabled = true
port = 54327
inspector_port = 54328

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
