
project_id = "jqkkhwoybcenxqpvodev"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[auth.email]
enable_signup = true

[functions.retell-webhook]
verify_jwt = false

[functions.sync-calls]

[functions.admin-update-balance]
