// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { ExtendedDatabase } from '@/types/supabase';

// Use environment variables from Vite
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    "Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file."
  );
}

// Create a placeholder client if the environment variables are missing (for development only)
// This prevents the app from crashing during development if .env is not set up
const devFallbackUrl = 'https://jqkkhwoybcenxqpvodev.supabase.co';
const devFallbackKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxa2tod295YmNlbnhxcHZvZGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDk4MzksImV4cCI6MjA2MzE4NTgzOX0._CudusgLYlJEv_AkJNGpjavmZNTqxXy4lvAv4laAGd8';

export const supabase = createClient<ExtendedDatabase>(
  SUPABASE_URL || devFallbackUrl, 
  SUPABASE_ANON_KEY || devFallbackKey,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Accept-Profile': 'public',
        'Content-Profile': 'public'
      }
    },
    db: {
      schema: 'public'
    }
  }
);

// 🚀 EXPONER EL CLIENTE GLOBALMENTE PARA DEBUGGING Y COMPATIBILIDAD
if (typeof window !== 'undefined') {
  (window as any).supabase = supabase;
  console.log('✅ Supabase client exposed globally for debugging');
}

// Export a function to check if we're using real credentials
export const hasValidSupabaseCredentials = () => {
  return Boolean(SUPABASE_URL && SUPABASE_ANON_KEY);
};